// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamTools.Data;

#nullable disable

namespace TeamTools.Data.PostgreSql.Migrations
{
    [DbContext(typeof(TeamToolsDbContext))]
    [Migration("20260909154204_SplitRoomAndPokerRound")]
    partial class SplitRoomAndPokerRound
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamTools.Core.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ChangedAfterReveal")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrganiser")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Vote")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("RoomId", "UserId")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("TeamTools.Core.Models.PokerRound", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoReveal")
                        .HasColumnType("boolean");

                    b.Property<string>("CurrentStory")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CurrentStoryNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CustomCards")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DeckType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedProvider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketQueue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TicketQueue");

                    b.Property<DateTimeOffset?>("TimerDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TimerDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("TimerPausedRemainingSeconds")
                        .HasColumnType("integer");

                    b.HasKey("RoomId");

                    b.ToTable("PokerRounds");
                });

            modelBuilder.Entity("TeamTools.Core.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowRoleChange")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrganiserUserId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("ReactionsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RoundResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision");

                    b.Property<bool>("Consensus")
                        .HasColumnType("boolean");

                    b.Property<string>("FinalEstimate")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Story")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoundResult");
                });

            modelBuilder.Entity("TeamTools.Core.Models.Participant", b =>
                {
                    b.HasOne("TeamTools.Core.Models.Room", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TeamTools.Core.Models.PokerRound", b =>
                {
                    b.HasOne("TeamTools.Core.Models.Room", "Room")
                        .WithOne("PokerRound")
                        .HasForeignKey("TeamTools.Core.Models.PokerRound", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TeamTools.Core.Models.LinkedIssue", "LinkedIssue", b1 =>
                        {
                            b1.Property<Guid>("PokerRoundRoomId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<double?>("StoryPoints")
                                .HasColumnType("double precision");

                            b1.Property<bool>("StoryPointsFieldAvailable")
                                .HasColumnType("boolean");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("PokerRoundRoomId");

                            b1.ToTable("PokerRounds");

                            b1.WithOwner()
                                .HasForeignKey("PokerRoundRoomId");
                        });

                    b.Navigation("LinkedIssue");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RoundResult", b =>
                {
                    b.HasOne("TeamTools.Core.Models.PokerRound", "Round")
                        .WithMany("RoundResults")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("TeamTools.Core.Models.PokerRound", b =>
                {
                    b.Navigation("RoundResults");
                });

            modelBuilder.Entity("TeamTools.Core.Models.Room", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("PokerRound");
                });
#pragma warning restore 612, 618
        }
    }
}
