// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamTools.Data;

#nullable disable

namespace TeamTools.Data.Sqlite.Migrations
{
    [DbContext(typeof(TeamToolsDbContext))]
    [Migration("20260910092226_AddRetroVotes")]
    partial class AddRetroVotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TeamTools.Core.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChangedAfterReveal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrganiser")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vote")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("RoomId", "UserId")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("TeamTools.Core.Models.PokerRound", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoReveal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentStory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStoryNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomCards")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketQueue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TicketQueue");

                    b.Property<DateTimeOffset?>("TimerDeadline")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimerDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimerPausedRemainingSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.ToTable("PokerRounds");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroBoard", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowMultiplePerItem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowParticipantGrouping")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anonymous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PhaseDeadline")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhaseDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteBudget")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.ToTable("RetroBoard");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("ColumnId");

                    b.HasIndex("GroupId");

                    b.ToTable("RetroCard");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("RetroColumn");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("RetroGroup");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoterUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("BoardId", "VoterUserId");

                    b.HasIndex("TargetKind", "TargetId");

                    b.ToTable("RetroVote");
                });

            modelBuilder.Entity("TeamTools.Core.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowRoleChange")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganiserUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReactionsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RoundResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Average")
                        .HasColumnType("REAL");

                    b.Property<bool>("Consensus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalEstimate")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Story")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoundResult");
                });

            modelBuilder.Entity("TeamTools.Core.Models.Participant", b =>
                {
                    b.HasOne("TeamTools.Core.Models.Room", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TeamTools.Core.Models.PokerRound", b =>
                {
                    b.HasOne("TeamTools.Core.Models.Room", "Room")
                        .WithOne("PokerRound")
                        .HasForeignKey("TeamTools.Core.Models.PokerRound", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TeamTools.Core.Models.LinkedIssue", "LinkedIssue", b1 =>
                        {
                            b1.Property<Guid>("PokerRoundRoomId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasMaxLength(8000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<double?>("StoryPoints")
                                .HasColumnType("REAL");

                            b1.Property<bool>("StoryPointsFieldAvailable")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");

                            b1.HasKey("PokerRoundRoomId");

                            b1.ToTable("PokerRounds");

                            b1.WithOwner()
                                .HasForeignKey("PokerRoundRoomId");
                        });

                    b.Navigation("LinkedIssue");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroBoard", b =>
                {
                    b.HasOne("TeamTools.Core.Models.Room", "Room")
                        .WithOne("RetroBoard")
                        .HasForeignKey("TeamTools.Core.Models.RetroBoard", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroCard", b =>
                {
                    b.HasOne("TeamTools.Core.Models.RetroBoard", "Board")
                        .WithMany("Cards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTools.Core.Models.RetroColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeamTools.Core.Models.RetroGroup", "Group")
                        .WithMany("Cards")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Board");

                    b.Navigation("Column");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroColumn", b =>
                {
                    b.HasOne("TeamTools.Core.Models.RetroBoard", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroGroup", b =>
                {
                    b.HasOne("TeamTools.Core.Models.RetroBoard", "Board")
                        .WithMany("Groups")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroVote", b =>
                {
                    b.HasOne("TeamTools.Core.Models.RetroBoard", "Board")
                        .WithMany("Votes")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RoundResult", b =>
                {
                    b.HasOne("TeamTools.Core.Models.PokerRound", "Round")
                        .WithMany("RoundResults")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("TeamTools.Core.Models.PokerRound", b =>
                {
                    b.Navigation("RoundResults");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroBoard", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Columns");

                    b.Navigation("Groups");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("TeamTools.Core.Models.RetroGroup", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("TeamTools.Core.Models.Room", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("PokerRound");

                    b.Navigation("RetroBoard");
                });
#pragma warning restore 612, 618
        }
    }
}
